// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArdaSDK.Kanban
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// </summary>
    public partial interface IKanbanClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IWorkspaceFoldersService.
        /// </summary>
        IWorkspaceFoldersService WorkspaceFoldersService { get; }

        /// <summary>
        /// Gets the IWorkspaceItemLogsService.
        /// </summary>
        IWorkspaceItemLogsService WorkspaceItemLogsService { get; }

        /// <summary>
        /// Gets the IWorkspaceItemsService.
        /// </summary>
        IWorkspaceItemsService WorkspaceItemsService { get; }

        /// <summary>
        /// Gets the IWorkspacesService.
        /// </summary>
        IWorkspacesService WorkspacesService { get; }

    }
}
