// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArdaSDK.Kanban
{
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for KanbanClient.
    /// </summary>
    public static partial class KanbanClientExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='folderId'>
            /// </param>
            /// <param name='archived'>
            /// </param>
            public static void List(this IKanbanClient operations, string folderId, bool? archived = default(bool?))
            {
                operations.ListAsync(folderId, archived).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='folderId'>
            /// </param>
            /// <param name='archived'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ListAsync(this IKanbanClient operations, string folderId, bool? archived = default(bool?), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.ListWithHttpMessagesAsync(folderId, archived, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
