// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArdaSDK.Kanban
{
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for WorkspaceFolders.
    /// </summary>
    public static partial class WorkspaceFoldersExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='folderId'>
            /// </param>
            /// <param name='input'>
            /// </param>
            public static void Create(this IWorkspaceFolders operations, string folderId, string input = default(string))
            {
                operations.CreateAsync(folderId, input).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='folderId'>
            /// </param>
            /// <param name='input'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task CreateAsync(this IWorkspaceFolders operations, string folderId, string input = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.CreateWithHttpMessagesAsync(folderId, input, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
