// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArdaSDK.Kanban.Models
{
    using ArdaSDK.Kanban;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class InputAppendLog
    {
        /// <summary>
        /// Initializes a new instance of the InputAppendLog class.
        /// </summary>
        public InputAppendLog()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InputAppendLog class.
        /// </summary>
        public InputAppendLog(string text = default(string), System.DateTime? createdDate = default(System.DateTime?), WorkspaceItemLogProperties property = default(WorkspaceItemLogProperties))
        {
            Text = text;
            CreatedDate = createdDate;
            Property = property;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Text")]
        public string Text { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreatedDate")]
        public System.DateTime? CreatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Property")]
        public WorkspaceItemLogProperties Property { get; set; }

    }
}
