// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArdaSDK.Kanban.Models
{
    using ArdaSDK.Kanban;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class WorkspaceItemProperties
    {
        /// <summary>
        /// Initializes a new instance of the WorkspaceItemProperties class.
        /// </summary>
        public WorkspaceItemProperties()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WorkspaceItemProperties class.
        /// </summary>
        public WorkspaceItemProperties(System.DateTime? startDate = default(System.DateTime?), System.DateTime? endDate = default(System.DateTime?), string description = default(string), bool? isWorkload = default(bool?), int? expertise = default(int?), int? complexity = default(int?), System.Guid? activityID = default(System.Guid?), System.Guid? lastAppointmentId = default(System.Guid?), IList<string> workloadUsers = default(IList<string>), IList<System.Guid?> metrics = default(IList<System.Guid?>), IList<System.Guid?> technologies = default(IList<System.Guid?>), IList<string> files = default(IList<string>))
        {
            StartDate = startDate;
            EndDate = endDate;
            Description = description;
            IsWorkload = isWorkload;
            Expertise = expertise;
            Complexity = complexity;
            ActivityID = activityID;
            LastAppointmentId = lastAppointmentId;
            WorkloadUsers = workloadUsers;
            Metrics = metrics;
            Technologies = technologies;
            Files = files;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartDate")]
        public System.DateTime? StartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EndDate")]
        public System.DateTime? EndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsWorkload")]
        public bool? IsWorkload { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Expertise")]
        public int? Expertise { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Complexity")]
        public int? Complexity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ActivityID")]
        public System.Guid? ActivityID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastAppointmentId")]
        public System.Guid? LastAppointmentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkloadUsers")]
        public IList<string> WorkloadUsers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Metrics")]
        public IList<System.Guid?> Metrics { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Technologies")]
        public IList<System.Guid?> Technologies { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Files")]
        public IList<string> Files { get; set; }

    }
}
