// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArdaSDK.Kanban.Models
{
    using ArdaSDK.Kanban;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class WorkspaceItemLogProperties
    {
        /// <summary>
        /// Initializes a new instance of the WorkspaceItemLogProperties class.
        /// </summary>
        public WorkspaceItemLogProperties()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WorkspaceItemLogProperties class.
        /// </summary>
        public WorkspaceItemLogProperties(int? laborHours = default(int?), double? expenses = default(double?))
        {
            LaborHours = laborHours;
            Expenses = expenses;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LaborHours")]
        public int? LaborHours { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Expenses")]
        public double? Expenses { get; set; }

    }
}
